pluginManagement {
	repositories {
		maven {
			name "Quilt"
			url "https://maven.quiltmc.org/repository/release"
		}
		maven {
			name "Fabric"
			url "https://maven.fabricmc.net/"
		}
		gradlePluginPortal()
	}
}

dependencyResolutionManagement {
	versionCatalogs {
		libs {
			def mc = "26.1.2"

			version("minecraft", mc)

			library("minecraft", "com.mojang", "minecraft").versionRef("minecraft")
			library("fabric-loader", "net.fabricmc:fabric-loader:0.18.4")

			library("fabric-api", "net.fabricmc.fabric-api:fabric-api:0.145.4+26.1.2")
			library("nucleoid-plasmid", "xyz.nucleoid:plasmid:0.7.0+${mc}")
		}
	}
}

rootProject.name = "quakecraft"
